// ==========================================
// FreelanceOS — Contract Generator Page
// ==========================================
// Generates a complete India-law service agreement LOCALLY (no API key needed)
// via src/services/contractTemplate.js — TDS (194J), GST/LUT, IP-on-payment,
// MSMED late-payment interest and arbitration clauses included. Optional
// "Refine with AI" polishes the text via the secure server proxy. The old code
// called Anthropic from the browser with no auth and never worked.
import React, { useState } from 'react';
import { useData } from '../context/DataContext';
import jsPDF from 'jspdf';
import { buildIndiaContract } from '../services/contractTemplate';
import { apiPost } from '../services/apiClient';
import {
  ScrollText, Loader2, Copy, Download, ChevronDown, MessageCircle, FileText, Sparkles,
} from 'lucide-react';

const PAYMENT_OPTIONS = ['50% Advance', '30-60-10', '100% on delivery', 'Custom'];
const INDIAN_STATES = [
  'Andhra Pradesh', 'Arunachal Pradesh', 'Assam', 'Bihar', 'Chhattisgarh',
  'Goa', 'Gujarat', 'Haryana', 'Himachal Pradesh', 'Jharkhand', 'Karnataka',
  'Kerala', 'Madhya Pradesh', 'Maharashtra', 'Manipur', 'Meghalaya', 'Mizoram',
  'Nagaland', 'Odisha', 'Punjab', 'Rajasthan', 'Sikkim', 'Tamil Nadu',
  'Telangana', 'Tripura', 'Uttar Pradesh', 'Uttarakhand', 'West Bengal',
  'Delhi', 'Chandigarh', 'Puducherry', 'Jammu & Kashmir', 'Ladakh',
];

export default function ContractGenerator() {
  const { state, addToast } = useData();
  const { settings } = state;

  const [form, setForm] = useState({
    yourName: settings.yourName || settings.businessName || '',
    clientName: '',
    description: '',
    value: '',
    paymentTerms: '50% Advance',
    startDate: '',
    endDate: '',
    revisions: 3,
    governingState: 'Maharashtra',
  });

  const [contract, setContract] = useState('');
  const [loading, setLoading] = useState(false);

  function set(key, val) { setForm(prev => ({ ...prev, [key]: val })); }

  // Build the India-law contract locally — instant, works with no API key.
  function generateContract() {
    if (!form.clientName || !form.description || !form.value) {
      addToast('Please fill in all required fields', 'error');
      return;
    }
    const text = buildIndiaContract(form, settings);
    setContract(text);
    addToast('Contract generated — review the India-specific clauses');
  }

  // Optional: polish the generated contract via the secure AI proxy.
  async function refineWithAI() {
    if (!contract) return;
    setLoading(true);
    try {
      const data = await apiPost('/ai/chat', {
        system: 'You are an Indian contract lawyer. Tighten and professionalise the agreement while KEEPING every India-specific clause intact (GST/LUT, TDS Section 194J, IP transfer on full payment, MSMED Act late-payment interest, arbitration & governing law). Return ONLY the final contract text, no commentary.',
        messages: [{ role: 'user', content: contract }],
      });
      if (data.text && data.text.trim()) {
        setContract(data.text.trim());
        addToast('Refined with AI');
      }
    } catch (e) {
      addToast(e.status === 503 ? 'AI not configured — keeping the template as-is' : 'AI refine unavailable right now', 'warning');
    } finally {
      setLoading(false);
    }
  }

  function copyContract() {
    navigator.clipboard.writeText(contract);
    addToast('Contract copied to clipboard!');
  }

  function downloadTxt() {
    const blob = new Blob([contract], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `contract-${form.clientName.replace(/\s+/g, '-')}.txt`;
    a.click();
    URL.revokeObjectURL(url);
    addToast('Contract downloaded as TXT!');
  }

  function downloadContractPDF() {
    const doc = new jsPDF({ unit: 'mm', format: 'a4' });

    // Title
    doc.setFontSize(16);
    doc.setFont('helvetica', 'bold');
    doc.text('FREELANCE SERVICE AGREEMENT', 105, 20, { align: 'center' });

    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');

    // Split contract text into lines that fit A4 width
    const lines = doc.splitTextToSize(contract, 175);
    let y = 35;
    const pageHeight = 280;

    lines.forEach(line => {
      if (y > pageHeight) {
        doc.addPage();
        y = 20;
      }
      doc.text(line, 17, y);
      y += 5;
    });

    // Footer
    const totalPages = doc.internal.getNumberOfPages();
    for (let i = 1; i <= totalPages; i++) {
      doc.setPage(i);
      doc.setFontSize(8);
      doc.setTextColor(150);
      doc.text(`Generated by FreelanceOS — ${new Date().toLocaleDateString('en-IN')}`, 105, 290, { align: 'center' });
    }

    doc.save(`Contract_${form.clientName.replace(/\s/g,'_')}_${new Date().toISOString().split('T')[0]}.pdf`);
    addToast('Contract PDF downloaded!');
  }

  function sendViaWhatsApp() {
    // Download the PDF first
    downloadContractPDF();

    // Pre-formatted message
    const message = `Hi ${form.clientName}, please find the service agreement for ${form.description.substring(0, 50)}${form.description.length > 50 ? '...' : ''} attached. Please review and confirm your acceptance. — ${form.yourName}`;
    const url = `https://wa.me/?text=${encodeURIComponent(message)}`;
    window.open(url, '_blank');
  }

  return (
    <div className="page-enter space-y-6">
      {/* Header */}
      <div>
        <h1 className="text-2xl font-bold text-dark-50 tracking-tight flex items-center gap-2">
          <ScrollText className="w-6 h-6 text-accent" />
          Contract Generator
        </h1>
        <p className="text-sm text-dark-300 mt-0.5">India-law service agreements — TDS, GST/LUT, IP-on-payment, MSMED interest & arbitration built in</p>
      </div>

      {/* Form */}
      <div className="glass-card p-6 space-y-4">
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          <div>
            <label className="input-label">Your Name / Business Name</label>
            <input value={form.yourName} onChange={e => set('yourName', e.target.value)} className="w-full" />
          </div>
          <div>
            <label className="input-label">Client Name *</label>
            <div className="relative">
              <input
                value={form.clientName}
                onChange={e => set('clientName', e.target.value)}
                className="w-full"
                placeholder="Type or select client"
                list="contract-clients"
              />
              <datalist id="contract-clients">
                {state.clients.map(c => <option key={c.id} value={c.name} />)}
              </datalist>
            </div>
          </div>
        </div>

        <div>
          <label className="input-label">Project Description *</label>
          <textarea
            value={form.description}
            onChange={e => set('description', e.target.value)}
            className="w-full min-h-[100px] resize-y"
            placeholder="Describe the project scope, objectives, and deliverables..."
            rows={4}
          />
        </div>

        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
          <div>
            <label className="input-label">Project Value (₹) *</label>
            <input type="number" value={form.value} onChange={e => set('value', e.target.value)} min="0" className="w-full" />
          </div>
          <div>
            <label className="input-label">Payment Terms</label>
            <div className="relative">
              <select value={form.paymentTerms} onChange={e => set('paymentTerms', e.target.value)} className="w-full appearance-none">
                {PAYMENT_OPTIONS.map(o => <option key={o} value={o}>{o}</option>)}
              </select>
              <ChevronDown className="absolute right-3 top-1/2 -translate-y-1/2 w-4 h-4 text-dark-400 pointer-events-none" />
            </div>
          </div>
          <div>
            <label className="input-label">Start Date</label>
            <input type="date" value={form.startDate} onChange={e => set('startDate', e.target.value)} className="w-full" />
          </div>
          <div>
            <label className="input-label">End Date</label>
            <input type="date" value={form.endDate} onChange={e => set('endDate', e.target.value)} className="w-full" />
          </div>
        </div>

        <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
          <div>
            <label className="input-label">Revision Rounds</label>
            <input type="number" value={form.revisions} onChange={e => set('revisions', Number(e.target.value))} min="0" max="10" className="w-full" />
          </div>
          <div>
            <label className="input-label">Governing Law State</label>
            <div className="relative">
              <select value={form.governingState} onChange={e => set('governingState', e.target.value)} className="w-full appearance-none">
                {INDIAN_STATES.map(s => <option key={s} value={s}>{s}</option>)}
              </select>
              <ChevronDown className="absolute right-3 top-1/2 -translate-y-1/2 w-4 h-4 text-dark-400 pointer-events-none" />
            </div>
          </div>
        </div>

        <button onClick={generateContract} className="btn-primary flex items-center gap-2">
          <ScrollText className="w-4 h-4" />
          Generate Contract
        </button>
      </div>

      {/* Preview */}
      {contract && (
        <div className="glass-card p-6 space-y-4">
          <div className="flex items-center justify-between">
            <h3 className="text-sm font-semibold text-dark-100">Generated Contract</h3>
            <button onClick={refineWithAI} disabled={loading} className="btn-secondary flex items-center gap-2 text-xs">
              {loading ? <Loader2 className="w-3.5 h-3.5 animate-spin" /> : <Sparkles className="w-3.5 h-3.5 text-accent" />}
              {loading ? 'Refining...' : 'Refine with AI'}
            </button>
          </div>
          <div className="bg-dark-700 rounded-lg p-5 max-h-[500px] overflow-y-auto custom-scroll">
            <pre className="text-sm text-dark-100 whitespace-pre-wrap font-sans leading-relaxed">{contract}</pre>
          </div>
          <div className="flex flex-wrap items-center gap-3">
            <button onClick={copyContract} className="btn-primary flex items-center gap-2">
              <Copy className="w-4 h-4" /> Copy
            </button>
            <button onClick={downloadContractPDF} className="btn-primary flex items-center gap-2 bg-gradient-to-r from-accent to-red-500 shadow-red-500/10">
              <FileText className="w-4 h-4" /> Download PDF
            </button>
            <button onClick={sendViaWhatsApp} className="btn-primary flex items-center gap-2 bg-gradient-to-r from-emerald-600 to-green-500 shadow-green-500/10 border-none">
              <MessageCircle className="w-4 h-4" /> Send via WhatsApp
            </button>
            <button onClick={downloadTxt} className="btn-secondary flex items-center gap-2">
              <Download className="w-4 h-4" /> Download TXT
            </button>
          </div>
          <p className="text-xs text-dark-400">Starting template, not legal advice — have a lawyer review before signing.</p>
        </div>
      )}
    </div>
  );
}
